### ISSUE TITLE
v0.6 of this add-on

### ISSUE THREAD

**Issue by acorncom** [locks/ember-welcome-page#4]
Background info on what we're trying to do here: https://github.com/emberjs/website/pull/2469) and also here: https://github.com/ember-cli/ember-cli/pull/5501

- [x] put in updated text (#7)
- [x] add-on checks to write (issue #5)
      - [x] Has an application.hbs been created?
      - [x] Has an index.hbs been created?
      - [x] Have any routes been created?
- [x] write acceptance tests to check the dummy app (issue #6)
- [x] open a PR to ember-cli/ember-cli with an npm dependency (see https://github.com/emberjs/website/pull/2469#issuecomment-188271620 for details)
    - [x] make [these suggested changes](https://github.com/emberjs/website/pull/2469#issuecomment-187622266) as part of this PR

**Comment by acorncom** [comment]
I've made all asked-for changes, closing this at this point
